name: json_diff
version: 0.1.3
author: Sam Rawlins <srawlins@google.com>
description: Utilities for diffing two JSON objects
homepage: https://github.com/google/dart-json_diff

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  collection: ^1.14.13
  diff_match_patch: ^0.3.0
dev_dependencies:
  test: ^1.6.4
  pedantic: ^1.9.2
